#!/usr/bin/env python3
"""Parse OCR text blobs and extract canonical server image paths."""

import argparse
import re
from pathlib import Path

import pandas as pd

PATH_RE = re.compile(
    r"/(?:19|20)\d{2}/[A-Za-z0-9._/-]*?\.(?:heic|jpe?g)",
    re.IGNORECASE,
)
TRAILING_ALPHA_BEFORE_EXT_RE = re.compile(
    r"(?<=\d)[A-Za-z](?=\.(?:heic|jpe?g)$)",
    re.IGNORECASE,
)


def _normalize_extracted_path(path: str) -> str:
    """Normalize OCR path artifacts while preserving expected server format."""
    return TRAILING_ALPHA_BEFORE_EXT_RE.sub("", path)


def extract_paths_from_text(text: str) -> list[str]:
    """Extract canonical server paths from a single OCR text blob."""
    candidates: list[str] = []

    candidates.extend(match.group(0) for match in PATH_RE.finditer(text))

    compact_text = "".join(text.split())
    candidates.extend(match.group(0) for match in PATH_RE.finditer(compact_text))

    normalized_paths: list[str] = []
    seen_paths: set[str] = set()
    for candidate in candidates:
        normalized = _normalize_extracted_path(candidate)
        if normalized not in seen_paths:
            normalized_paths.append(normalized)
            seen_paths.add(normalized)

    return normalized_paths


def extract_server_paths_from_rows(rows: list[dict]) -> list[str]:
    """Extract unique server paths from OCR rows produced by extract_image_text."""
    server_paths: list[str] = []
    seen_paths: set[str] = set()

    for row in rows:
        text = str(row.get("extracted_text", ""))
        for path in extract_paths_from_text(text):
            if path not in seen_paths:
                server_paths.append(path)
                seen_paths.add(path)

    return server_paths


def extract_server_paths_from_csv(input_csv: Path) -> list[str]:
    """Load OCR text CSV and extract unique server paths."""
    rows = pd.read_csv(input_csv).to_dict(orient="records")
    return extract_server_paths_from_rows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract server paths from OCR text")
    parser.add_argument(
        "--input-csv",
        type=Path,
        required=True,
        help="Input CSV generated by extract_image_text.py",
    )
    parser.add_argument(
        "--output-csv", type=Path, required=True, help="Output CSV for server paths"
    )

    args = parser.parse_args()

    input_csv = args.input_csv.expanduser().resolve()
    output_csv = args.output_csv.expanduser().resolve()

    server_paths = extract_server_paths_from_csv(input_csv)

    for path in server_paths:
        print(path)

    pd.DataFrame(server_paths, columns=["server_path"]).to_csv(output_csv, index=False)


if __name__ == "__main__":
    main()
