"""CLI entrypoints for photo_ocr."""

import argparse
from pathlib import Path

import pandas as pd

from .extract import extract_text_from_images
from .match_paths import (
    build_available_paths,
    extract_server_paths_from_csv,
    extract_server_paths_from_rows,
    find_fuzzy_match,
)
from .trash import move_paths_to_trash, validate_folder_name


def extract_text_main() -> None:
    parser = argparse.ArgumentParser(description="Extract OCR text from images")
    parser.add_argument(
        "--download-folder",
        type=Path,
        required=True,
        help="Folder containing images to scan",
    )
    parser.add_argument(
        "--output-csv", type=Path, required=True, help="Output CSV for OCR text"
    )
    parser.add_argument(
        "--img-pattern",
        type=str,
        default="IMG_*",
        help="Glob pattern for image files (default: IMG_*)",
    )

    args = parser.parse_args()

    download_folder = args.download_folder.expanduser().resolve()
    output_csv = args.output_csv.expanduser().resolve()

    rows = extract_text_from_images(download_folder, img_pattern=args.img_pattern)
    pd.DataFrame(rows, columns=["image_file", "extracted_text"]).to_csv(
        output_csv, index=False
    )


def extract_paths_main() -> None:
    parser = argparse.ArgumentParser(description="Extract server paths from OCR text")
    parser.add_argument(
        "--input-csv",
        type=Path,
        required=True,
        help="Input CSV generated by photo-ocr-extract-text",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        required=True,
        help="Output CSV for server paths",
    )

    args = parser.parse_args()

    input_csv = args.input_csv.expanduser().resolve()
    output_csv = args.output_csv.expanduser().resolve()

    server_paths = extract_server_paths_from_csv(input_csv)

    for path in server_paths:
        print(path)

    pd.DataFrame(server_paths, columns=["server_path"]).to_csv(output_csv, index=False)


def extract_server_paths_main() -> None:
    parser = argparse.ArgumentParser(description="Extract server paths from images")
    parser.add_argument(
        "--download-folder",
        type=Path,
        required=True,
        help="Folder containing images to scan (default: ~/Downloads/images-to-delete)",
    )
    parser.add_argument(
        "--output-csv", type=Path, required=True, help="Output CSV file path"
    )
    parser.add_argument(
        "--img-pattern",
        type=str,
        default="IMG_*",
        help="Glob pattern for image files (default: IMG_*)",
    )

    args = parser.parse_args()

    download_folder = args.download_folder.expanduser().resolve()
    output_csv = args.output_csv.expanduser().resolve()

    rows = extract_text_from_images(download_folder, img_pattern=args.img_pattern)
    server_paths = extract_server_paths_from_rows(rows)

    for path in server_paths:
        print(path)

    pd.DataFrame(server_paths, columns=["server_path"]).to_csv(output_csv, index=False)


def check_filenames_main() -> None:
    parser = argparse.ArgumentParser(description="Check and correct file paths")
    parser.add_argument(
        "--photo-folder",
        type=Path,
        required=True,
        help="Base photo server path (e.g., /Volumes/photo)",
    )
    parser.add_argument(
        "--base-folder",
        type=Path,
        required=True,
        help="Base folder for CSV files (default: ~/Downloads/images-to-delete)",
    )
    parser.add_argument(
        "--input-csv",
        type=str,
        required=True,
        help="Input CSV file name (e.g., server_paths.csv)",
    )
    parser.add_argument(
        "--output-csv",
        type=str,
        default=None,
        help="Output CSV file name (default: input-csv -> input-csv_corrected.csv)",
    )
    parser.add_argument(
        "--cutoff",
        type=float,
        default=0.75,
        help="Fuzzy matching cutoff (default: 0.75)",
    )

    args = parser.parse_args()

    base_dir = args.base_folder.expanduser().resolve()
    photo_folder = args.photo_folder.expanduser().resolve()
    csv_file = base_dir / args.input_csv
    input_path = Path(args.input_csv)
    default_output = f"{input_path.stem}_corrected{input_path.suffix}"
    output_csv = csv_file.with_name(args.output_csv or default_output)

    df = pd.read_csv(csv_file)
    df["corrected_server_path"] = df["server_path"].astype(str)

    available_paths = build_available_paths(photo_folder)
    corrected = []

    for server_path in df["server_path"].astype(str):
        clean_path = server_path.lstrip("/")
        src = photo_folder / clean_path

        if src.exists():
            corrected.append(server_path)
            continue

        print(f"Source path does not exist: {src}")

        match = find_fuzzy_match(clean_path, available_paths, cutoff=args.cutoff)

        if match:
            corrected_path = f"/{match}"
            print(f"  -> Suggested correction: {corrected_path}")
            corrected.append(corrected_path)
        else:
            corrected.append(server_path)

    df["corrected_server_path"] = corrected
    df.to_csv(output_csv, index=False)

    print(f"Wrote corrected paths to {output_csv}")


def move_to_trash_main() -> None:
    parser = argparse.ArgumentParser(description="Move files to trash based on CSV list")
    parser.add_argument(
        "--photo-folder",
        type=Path,
        required=True,
        help="Base photo server path (e.g., /Volumes/photo)",
    )
    parser.add_argument(
        "--trash-folder",
        type=Path,
        default=None,
        help="Trash directory (default: <photo-folder>/<trash-folder-name>)",
    )
    parser.add_argument(
        "--csv-file",
        type=Path,
        required=True,
        help="CSV file with list of paths to move to trash",
    )
    parser.add_argument(
        "--trash-folder-name",
        type=validate_folder_name,
        default="trash",
        help=(
            "Name of the trash folder when --trash-folder is not specified "
            "(default: trash)"
        ),
    )

    args = parser.parse_args()

    photo_folder = args.photo_folder.expanduser().resolve()
    csv_file = args.csv_file.expanduser().resolve()

    if args.trash_folder is not None:
        trash = args.trash_folder.expanduser().resolve()
    else:
        trash = photo_folder / args.trash_folder_name

    move_paths_to_trash(photo_folder=photo_folder, trash=trash, csv_file=csv_file)
